# Supabase local development configuration
project_id = "standard-practices"

[api]
enabled = true
port = 54321
schemas = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "env(SITE_URL)"
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[functions.verify_jwt]
enabled = false
